### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by WingOfChicken** [masamesa/Twitch-Clip-Archiver#3]
Hello Again,

v1.2 is resulting in the below 2 errors, and ultimately crash. The first time I didn't notice as the command prompt closed itself as soon as the unhandled exception occurred - second time I was lucky on timing with screenshot. It occurred on the same clip both times.

https://gyazo.com/3c1f673c237a283fc66eaa97e08dbd2c

https://gyazo.com/7b6e3a07e18d9d4b38ce66a4b6d58813

Thanks again for your work on this - make sure you get some sleep before you tackle any more!

**Comment by masamesa** [comment]
Looking into it at the moment, thanks for the contant reports!

**Comment by masamesa** [comment]
Took me a little longer due to having to clean up some messy code to fully make sure this never occurs by mishap again. v1.3 should solve this issue; however, if it doesn't I will be leaving this thread open for 24 hours or until you close it. <a href="https://github.com/masamesa/Twitch-Clip-Archiver/releases/tag/1.3"> Please download here</a>(https://github.com/masamesa/Twitch-Clip-Archiver/releases/tag/1.3) 

Thanks, 
Alexander

**Comment by WingOfChicken** [comment]
Hello again,

Tested - unfortunately still crashed. It got further this time (about twice as far), but closed before I could screen-cap the error.

I'll try again now and edit this post if I can get another screenshot.

Side note: is there an error log that spits out the clips it fails on  (like my first screenshot in the original post)? I could just go through manually later and download the few that seem to fail if there was a list, or even better a list with links.

**Comment by masamesa** [comment]
Unfortunate; I was intending on adding in that last feature tomorrow, but I'll throw something together that logs the failed clips along with it generating a crash report. 

Very sorry this is happening, I'm not quite sure why until I get a stack trace to work with. Update will be pushed in ETA 10-15 minutes. I'll DM you on twitter when it's ready.

**Comment by masamesa** [comment]
Bug fixed.
